# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': '\u5e16\u5b50'},
        ),
    ]
